apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: chrome
  name: chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chrome
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chrome
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: chrome
              topologyKey: kubernetes.io/hostname
      containers:
        - image: browserless/chrome:latest
          name: chrome
          imagePullPolicy: IfNotPresent
          ports:
            - name: chrome
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /pressure
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 5
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: DEBUG
              value: "browserless/chrome*"
            - name: EXIT_ON_HEALTH_FAILURE
              value: "true"
            - name: ENABLE_DEBUGGER
              value: "false"
            - name: MAX_CONCURRENT_SESSIONS
              valueFrom:
                configMapKeyRef:
                  key: MAX_CONCURRENT_SESSIONS
                  name: env-vars
            - name: PREBOOT_CHROME
              value: "false"
            - name: CONNECTION_TIMEOUT
              value: "1200000"
              