export declare enum LoginError {
    CREDENTIALS_MISSING = "CREDENTIALS_MISSING",
    ENCRYPTION_KEY_MISSING = "ENCRYPTION_KEY_MISSING",
    ENCRYPTION_VERSION_UNSUPPORTED = "ENCRYPTION_VERSION_UNSUPPORTED",
    COULD_NOT_LOGIN = "COULD_NOT_LOGIN"
}
