export interface SegmentMessage {
    anonymousId?: string | number
    properties?: any
    context?: any
}

export enum TrackingEvent {
    USER_REGISTERED = 'USER_REGISTERED',
    USER_LOGIN = 'USER_LOGIN',
    USER_OAUTH_REGISTERED = 'USER_OAUTH_REGISTERED',
    USER_OAUTH_LOGIN = 'USER_OAUTH_LOGIN',
    USER_FORGOT_PASSWORD = 'USER_FORGOT_PASSWORD',
    USER_RESET_PASSWORD = 'USER_RESET_PASSWORD',
    USER_UPDATE_INFO = 'USER_UPDATE_INFO',
    USER_VERIFY_EMAIL = 'USER_VERIFY_EMAIL',
    USER_CANCEL_ACCOUNT = 'USER_CANCEL_ACCOUNT',
    USER_UPDATE_SETTINGS = 'USER_UPDATE_SETTINGS',

    WORKFLOW_CREATE = 'WORKFLOW_CREATE',
    WORKFLOW_UPDATE = 'WORKFLOW_UPDATE',
    WORKFLOW_REMOVE = 'WORKFLOW_REMOVE',
    WORKFLOW_RUN = 'WORKFLOW_RUN',

    JOB_CREATE = 'JOB_CREATE',
    JOB_RUN = 'JOB_RUN',
    JOB_REMOVE = 'JOB_REMOVE',
    JOB_PAUSE = 'JOB_PAUSE',
    JOB_RESUME = 'JOB_RESUME',

    INTEGRATION_REMOVE = 'INTEGRATION_REMOVE',
    INTEGRATION_TOGGLE = 'INTEGRATION_TOGGLE',

    CATALOG_PICK_ITEM = 'CATALOG_PICK_ITEM',

    PAYMENT_UPDATE = 'PAYMENT_UPDATE',
    PAYMENT_DISABLED = 'PAYMENT_DISABLED',
    PAYMENT_ADD_REFERRAL_CREDITS = 'PAYMENT_ADD_REFERRAL_CREDITS',
    PAYMENT_CHANGE_PLAN = 'PAYMENT_CHANGE_PLAN',
    PAYMENT_CREDITS_REFILLED = 'PAYMENT_CREDITS_REFILLED'
}
