apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: frontend-certificate
spec:
  dnsNames:
    - app.bitpull.io
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: letsencrypt-frontend
