export declare enum PaginationError {
    GOTOPERPAGE_NODE_MISSING = "GOTOPERPAGE_NODE_MISSING",
    PAGINATION_METHOD_MISSING = "PAGINATION_METHOD_MISSING",
    NEXT_LINK_MISSING = "NEXT_LINK_MISSING",
    NO_LINKS_SPECIFIED = "NO_LINKS_SPECIFIED"
}
