export enum LoginError {
    CREDENTIALS_MISSING = 'CREDENTIALS_MISSING',
    ENCRYPTION_KEY_MISSING = 'ENCRYPTION_KEY_MISSING',
    ENCRYPTION_VERSION_UNSUPPORTED = 'ENCRYPTION_VERSION_UNSUPPORTED'
}
