enum UserConstants {
    LOGIN = 'LOGIN',
    LOGIN_SUCCESS = 'LOGIN_SUCCESS',
    LOGIN_FAILED = 'LOGIN_FAILED',

    REGISTER = 'REGISTER',
    REGISTER_SUCCESS = 'REGISTER_SUCCESS',
    REGISTER_FAILED = 'REGISTER_FAILED',

    OAUTH = 'OAUTH',
    OAUTH_SUCCESS = 'OAUTH_SUCCESS',
    OAUTH_FAILED = 'OAUTH_FAILED',

    LOAD_USER = 'LOAD_USER',
    LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS',
    LOAD_USER_FAILED = 'LOAD_USER_FAILED',

    VERIFY_EMAIL = 'VERIFY_EMAIL',
    VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS',
    VERIFY_EMAIL_FAILED = 'VERIFY_EMAIL_FAILED',

    UPDATE_INFORMATION = 'UPDATE_INFORMATION',
    UPDATE_INFORMATION_SUCCESS = 'UPDATE_INFORMATION_SUCCESS',
    UPDATE_INFORMATION_FAILED = 'UPDATE_INFORMATION_FAILED',

    LOGOUT = 'LOGOUT'
}

export default UserConstants
