"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.NodeType = void 0;
var NodeType;
(function (NodeType) {
    NodeType["COLLECT"] = "COLLECT";
    NodeType["PAGINATION"] = "PAGINATION";
    NodeType["HTML"] = "HTML";
    NodeType["HTML_LINKED"] = "HTML_LINKED";
    NodeType["HTML_MULTIPLE"] = "HTML_MULTIPLE";
    NodeType["CLICK"] = "CLICK";
    NodeType["CLICK_MULTIPLE"] = "CLICK_MULTIPLE";
    NodeType["LOGIN"] = "LOGIN";
    NodeType["FUNCTION"] = "FUNCTION";
    NodeType["EXCEL"] = "EXCEL";
    NodeType["CSV"] = "CSV";
    NodeType["JSON"] = "JSON";
    NodeType["SCREENSHOT"] = "SCREENSHOT";
    NodeType["PDF"] = "PDF";
    NodeType["SLACK"] = "SLACK";
    NodeType["EMAIL"] = "EMAIL";
    NodeType["DROPBOX"] = "DROPBOX";
    NodeType["STORAGE"] = "STORAGE";
    NodeType["GOOGLE_DRIVE"] = "GOOGLE_DRIVE";
    NodeType["ONEDRIVE"] = "ONEDRIVE";
    NodeType["GITHUB"] = "GITHUB";
    NodeType["WEBHOOK"] = "WEBHOOK";
    NodeType["WAIT"] = "WAIT";
    NodeType["SCROLL"] = "SCROLL";
})(NodeType = exports.NodeType || (exports.NodeType = {}));
//# sourceMappingURL=node.js.map