export enum HtmlError {
    LINKED_FIELD_MISSING = 'LINKED_FIELD_MISSING',
    LINKED_FIELD_NOT_FOUND = 'LINKED_FIELD_NOT_FOUND',
    LINKS_MISSING = 'LINKS_MISSING',
    INVALID_URL = 'INVALID_URL',
    NAVIGATION_FAILED = 'NAVIGATION_FAILED'
}
