export enum TrackingEvent {
    USER_LOGOUT = 'USER_LOGOUT',
    WORKFLOW_CANCEL_RUN = 'WORKFLOW_CANCEL_RUN',
    WORKFLOW_VIEW_LOGS = 'WORKFLOW_VIEW_LOGS',
    REFERRAL_COPY_LINK = 'REFERRAL_COPY_LINK'
}
