export declare enum StorageError {
    STORAGE_OPTIONS_MISSING = "STORAGE_OPTIONS_MISSING",
    AWS_BUCKET_MISSING = "AWS_BUCKET_MISSING",
    AWS_ACCESS_KEY_ID_MISSING = "AWS_ACCESS_KEY_ID_MISSING",
    AWS_SECRET_ACCESS_KEY_MISSING = "AWS_SECRET_ACCESS_KEY_MISSING",
    INVALID_PARENT_TYPE = "INVALID_PARENT_TYPE",
    STORAGE_FAILED = "STORAGE_FAILED"
}
