apiVersion: v1
kind: Service
metadata:
  labels:
    name: chrome
  name: chrome
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: chrome
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    name: chrome
  name: chrome
spec:
  selector:
    matchLabels:
      app: chrome
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chrome
    spec:
      containers:
      - image: browserless/chrome:latest
        name: chrome
        ports:
        - name: chrome
          containerPort: 3000
        env:
          - name: HOST
            value: "0.0.0.0"
          # - name: CONNECTION_TIMEOUT
          #   value: "900000"
          - name: ENABLE_DEBUGGER
            value: "false"
          - name: MAX_CONCURRENT_SESSIONS
            value: "10"
          # - name: PREBOOT_CHROME
          #   value: "true"
          - name: DEBUG
            value: "browserless/chrome*"
          - name: EXIT_ON_HEALTH_FAILURE
            value: "true"
      # - image: gcr.io/scrippy/pressure:latest
      #   name: pressure
      #   env:
      #     - name: PUPPETEER_URL
      #       value: "http://chrome"