apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    backend: backend
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: gcr.io/bitpull/backend:latest
        name: backend
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              key: API_URL
              name: backend-env
        - name: APP_URL
          valueFrom:
            configMapKeyRef:
              key: APP_URL
              name: backend-env
        - name: DATABASE_URI
          valueFrom:
            configMapKeyRef:
              key: DATABASE_URI
              name: backend-env
        - name: PUPPETEER_ENDPOINT
          value: ws://chrome:3000
        - name: GROWSURF_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: growsurf
              name: token
        - name: GROWSURF_CAMPAIGN_ID
          valueFrom:
            configMapKeyRef:
              key: GROWSURF_CAMPAIGN_ID
              name: backend-env
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            configMapKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: backend-env
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              key: AWS_REGION
              name: backend-env
        - name: AWS_S3_BUCKET
          valueFrom:
            configMapKeyRef:
              key: AWS_S3_BUCKET
              name: backend-env
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: aws
              name: key
        - name: DROPBOX_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              key: DROPBOX_CLIENT_ID
              name: backend-env
        - name: DROPBOX_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: dropbox
              name: secret
        - name: EMAIL_FROM_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: EMAIL_FROM_ADDRESS
              name: backend-env
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              key: GOOGLE_CLIENT_ID
              name: backend-env
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: google
              name: secret
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: jwt-secret
              name: key
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              key: encryption-key
              name: key
        - name: ONEDRIVE_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              key: ONEDRIVE_CLIENT_ID
              name: backend-env
        - name: ONEDRIVE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: onedrive
              name: secret
        - name: GITHUB_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              key: GITHUB_CLIENT_ID
              name: backend-env
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: github
              name: key
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              key: sendgrid
              name: key
        - name: SLACK_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              key: SLACK_CLIENT_ID
              name: backend-env
        - name: SLACK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: slack
              name: key
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: stripe
              name: key
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              key: stripe
              name: webhook